/// A provider-neutral analytics payload generated by an allowlisted technical event.
struct AnalyticsPayload: Equatable, Sendable {
    let name: String
    let parameters: [String: String]
}

/// Screen identifiers permitted in technical analytics events.
enum AnalyticsScreen: String, Sendable {
    case bootstrap
}

/// The closed set of technical analytics events permitted by the application.
enum AnalyticsEvent: Equatable, Sendable {
    case appOpened
    case screenViewed(AnalyticsScreen)

    /// The stable provider payload for this allowlisted event.
    var payload: AnalyticsPayload {
        switch self {
        case .appOpened:
            AnalyticsPayload(name: "app_opened", parameters: [:])
        case let .screenViewed(screen):
            AnalyticsPayload(
                name: "screen_viewed",
                parameters: ["screen": screen.rawValue]
            )
        }
    }
}

/// The closed set of non-PII diagnostics permitted for crash reporting.
enum CrashDiagnostic: Int, Equatable, Sendable {
    case controlledValidation = 1_001

    /// The stable error domain paired with each diagnostic code.
    var errorDomain: String {
        "com.plusprojects.FranAlonso.telemetry"
    }
}

/// The owner-controlled consent state that gates telemetry collection and emission.
enum TelemetryConsent: Sendable {
    case denied
    case granted

    var isGranted: Bool {
        self == .granted
    }
}
